repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--config', '.markdownlint.json']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, html, css, javascript, json, yaml]

  - repo: local
    hooks:
      - id: cleanup-preview-files
        name: Clean up preview files
        entry: bash -c 'find articles -name "*_files" -type d -exec rm -rf {} + 2>/dev/null || true; find articles -name "*.html" -type f -delete 2>/dev/null || true; echo "✅ Cleaned up preview files"'
        language: system
        pass_filenames: false
        always_run: true
