name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules --config .markdownlint.json
        continue-on-error: false

  html-css-lint:
    name: HTML/CSS Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install HTMLHint and stylelint
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Run HTMLHint
        run: htmlhint '**/*.html' --config .htmlhintrc
        continue-on-error: false

      - name: Run stylelint
        run: stylelint '**/*.css' --config .stylelintrc.json
        continue-on-error: false

  prettier-format-check:
    name: Prettier Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check formatting
        run: prettier --check "**/*.{md,html,css,js,json,yml,yaml}"

  quarto-render:
    name: Quarto Document Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check Quarto documents
        run: |
          if ls articles/*.qmd 1> /dev/null 2>&1; then
            echo "Found Quarto documents, validating YAML frontmatter..."
            python3 .github/scripts/validate-quarto.py articles/*.qmd
            echo "✅ All Quarto documents validated"
          else
            echo "ℹ️  No .qmd files found"
          fi
